apiVersion: v1
kind: ServiceAccount
metadata:
  name: <name-of-service>

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: <name-of-role>
rules:
- apiGroups: ["extensions", "apps", ""]
  resources: ["services", "deployments", "pods"]
  verbs: ["get", "create", "update", "patch", "list", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <name-of-rolebinding>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: <name-of-role>
subjects:
- kind: ServiceAccount
  name: <name-of-service>

  namespace: default
