apiVersion: v1
kind: ServiceAccount
metadata:
  name: sampleservice


---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: samplerole
rules:
- apiGroups: ["extensions", "apps", ""]
  resources: ["services", "deployments", "pods"]
  verbs: ["get", "create", "update", "patch", "list", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: samplerolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: samplerole
subjects:
- kind: ServiceAccount
  name: sampleservice

  namespace: default
